# Generated by Django 5.1.6 on 2025-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskApp', '0002_faq_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('agent', 'Helpdesk Agent')], max_length=25),
        ),
    ]
