# Generated by Django 5.1.6 on 2025-06-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskApp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('network', 'Network'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
